title: Excit3D Wiki
description: Wiki for Excit3D.
theme: "just-the-docs"
# logo: "/assets/images/logo.png"
color_scheme: "violet"

search_enabled: true
search.rel_url: true

url: https://excit3dprints.com
